name: 🍌 Auto-Deploy to Pi

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    name: 🚀 Deploy to Pi Server
    runs-on: ubuntu-latest
    
    steps:
    - name: 🍌 Checkout code
      uses: actions/checkout@v4
      
    - name: 🔑 Setup SSH
      uses: webfactory/ssh-agent@v0.8.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
        
    - name: 🧪 Add server to known hosts
      run: |
        ssh-keyscan -H ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts
        
    - name: 🚀 Deploy to server
      run: |
        ssh ${{ secrets.SSH_USER }}@${{ secrets.SERVER_HOST }} << 'EOF'
          echo "🍌 Starting deployment..."
          
          # Navigate to project directory
          cd ${{ secrets.PROJECT_PATH }}
          
          # Run deployment script
          bash deploy.sh
          
          echo "🍌 Deployment complete!"
        EOF
        
    - name: 📊 Post-deployment health check
      run: |
        echo "🍌 Waiting for service to start..."
        sleep 10
        
        # Health check
        if curl -f http://${{ secrets.SERVER_HOST }}:${{ secrets.SERVER_PORT }}/health; then
          echo "✅ Health check passed!"
        else
          echo "❌ Health check failed!"
          exit 1
        fi
        
    - name: 🍌 Deployment notification
      if: always()
      run: |
        if [ ${{ job.status }} == 'success' ]; then
          echo "🍌 BANANA-POWERED DEPLOYMENT SUCCESSFUL! 🍌"
          echo "🚀 Pi API Hub is now running the latest code!"
        else
          echo "🚨 DEPLOYMENT FAILED! Check logs for details."
        fi